default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:

development:
  <<: *default
  database: tracker_development
#  socket: /tmp/mysql.sock

test:
  <<: *default
  database: tracker_test

production:
  <<: *default
  database: tracker_production
